# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows:
    name: Windows Tests
    runs-on: "windows-latest"
    strategy:
      fail-fast: True
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          auto-update-conda: true
          python-version: {{ "${{ matrix.python-version }}" }}
          channels: conda-forge
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Create Conda environment with the rights deps
        shell: bash -l {0}
        run: |
          {{ "conda create -n zarr-env python==${{matrix.python-version}} zarr pip" }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda activate zarr-env
          python -m pip install --upgrade pip
          python -m pip install -U pip setuptools wheel
          python -m pip install -r requirements_dev_numpy.txt -r requirements_dev_minimal.txt -r requirements_dev_optional.txt
          python -m pip install .
          python -m pip freeze
      - name: Run Tests
        shell: bash -l {0}
        run: |
          conda activate zarr-env
          pytest -sv --timeout=300
        env:
          ZARR_V3_EXPERIMENTAL_API: 1
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
